# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Rahul Gandhi
title: Lead Frontend Engineer
email: rahulgandhi38@gmail.com
email_title: Email
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  gandhirahul
stackoverflow_username: "rahul-gandhi"
linkedin_username: rahulgandhi92
# youtube_username: jekyll

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/my_image.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a frontend engineer with <mark>10+ years</mark> of experience building scalable, user-focused web apps across startups and global tech companies. I've led projects from scratch, contributed to high-traffic platforms, and helped shape frontend architecture that balances performance, maintainability, and great UX. 
  
  My main strength lies in <mark>JavaScript</mark> and <mark>React</mark>, whether it's designing reusable component systems, improving load times, or rolling out features quickly without compromising quality. I enjoy solving real product problems with clean, reliable code.
  
  I've worked closely with cross-functional teams, mentored junior developers, and taken ownership of end-to-end delivery. I care deeply about craftsmanship, collaboration, and shipping things that matter.


content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Bumble
        sub_title: Lead Frontend Engineer
        caption: Feb 2018 - Present
        quote: "Led critical frontend efforts at scale across Bumble and Badoo, shipping fast, accessible experiences to millions of users while mentoring teams and improving internal tooling."
        skills: "React, JavaScript, TypeScript, Design Systems, Micro-frontends, Performance Optimization, Accessibility, Webpack, CI/CD, Internationalization, Mentorship, Cross-team Collaboration"
        list:
          - text: Led multiple end-to-end web projects, improving page load time by up to 40% through performance optimizations and refactoring.
          - text: Directed teams (upto 3-4 engineers) and ensured timely delivery of scalable, user-friendly features used by millions.
          - text: Spearheaded internal tools that reduced manual operational tasks by 30%, improving team efficiency.
          - text: Mentored junior engineers and created onboarding guides, cutting ramp-up time by 25%.
          - text: Played a key role in hiring, interviewed 50+ candidates and helped build a high-performing frontend team.
          - text: Championed accessibility and internationalization initiatives, enabling consistent UX across languages and global markets.
          - text: Collaborated closely with product, design, and backend to drive shared ownership and deliver high-impact features.

      - layout: left
        title: Roposo
        sub_title: Frontend Engineer
        caption: Dec 2015 - Jan 2018
        quote: "Worked in a fast-paced startup environment, building full-stack web apps and internal tools using React and the MERN stack, while contributing to core user-facing products."
        skills: "React, JavaScript, MERN Stack, Node.js, MongoDB, Express.js, Material UI, Responsive Design, Full-Stack Development, Rapid Prototyping, Product Iteration"
        list:
          - text: Developed a responsive desktop and mobile web app from scratch using React, resulting in twice an increase in user engagement.
          - text: Built a full-stack Blogger Tool using the MERN stack to support influencer content publishing, reducing campaign turnaround time by 50%.
          - text: Designed and implemented a user management dashboard with Material UI, boosting internal workflow efficiency.
          - text: Took full ownership of features, from frontend to backend and iterating quickly based on real user feedback and business needs.
          - text: Gained exposure to a wide range of responsibilities in a lean team, accelerating development speed and product delivery.

      - layout: left
        title: Tata Consultancy Services
        sub_title: Frontend Developer
        caption: Nov 2014 - Nov 2015
        quote: "Kickstarted my career working on enterprise web apps, focusing on frontend development with jQuery and AngularJS in a large-scale, client-facing environment."
        skills: "jQuery, AngularJS, JavaScript, HTML, CSS, Enterprise Applications, Cross-Browser Compatibility, Team Collaboration"
        list:
          - text: Developed and maintained frontend features for enterprise applications using jQuery, ensuring usability and cross-browser consistency.
          - text: Played a key role in migrating legacy jQuery codebases to AngularJS, improving maintainability and reducing bug count by 40%.
          - text: Collaborated with global delivery teams and gained experience working within large, structured engineering processes.


  - title: Education
    layout: list
    content:
      - layout: left
        title: USICT, GGSIPU
        sub_title: B.Tech in Information Technology
        caption: 2010 - 2014
        description: |
          University School of Information, Communication & Technology (USICT), GGSIPU — New Delhi, India
          Graduated 2014 · GPA: <mark>75.18%</mark> (First-Class Honours)
        sub_description_heading: "Web Developer Intern — Rubus Labs (BlackBerry India)"
        list: 
          - text: Web Developer Intern
          - text: September 2013
          - text: Built web-based apps for the BlackBerry 10 OS using HTML5, CSS3, JavaScript, and jQuery.

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Front End Development Certification
        sub_title: FreeCodeCamp
        caption: Issued Dec 2016
        link: https://www.freecodecamp.org/certification/gandhirahul/legacy-front-end
        link_text: Certificate
        quote: Completed FreeCodeCamp's rigorous Front End Development Certification
        list: 
          - text: Completed FE dev program representing approximately 300 hours of work.
          - text: Gained advanced proficiency in modern web development tools and best practices.
          - text: Built responsive, accessible UIs with a focus on performance and maintainability.
          - text: Applied industry-standard design patterns across projects.

  - title: Scholastic Achievements
    layout: text
    content: | #
        | ----------- | ----------- |
        | 2014   | Received cash reward in Tizen Developer Offer competition.        |
        | 2013   | Won Devworx Blackberry 10 Competition and received a cash reward in Blackberry10 Port-a-Thon competition.        |
        | 2010   | Achieved All India Rank <b>254</b> in CET (Common Entrance Test).        |

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Outside of work, I like staying active and curious. I enjoy playing table tennis and badminton, and I often head out for hikes or treks to unwind and challenge myself physically.

      Fitness is important to me, so I regularly hit the gym to keep both my body and mind sharp.

      When it's time to slow down, I dig into self-help books for personal growth or explore tech articles and videos to stay on top of new trends and ideas in the industry.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
