# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Rahul Gandhi
title: Lead Frontend Engineer
email: rahulgandhi38@gmail.com
email_title: Email
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  gandhirahul
stackoverflow_username: "rahul-gandhi"
linkedin_username: rahulgandhi92
# youtube_username: jekyll

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/my_image.png
about_content: | # this will include new lines to allow paragraphs
  A highly skilled and dedicated frontend engineer with over <mark>10 years</mark> of professional experience working in startups, small scale or large scale companies.
  
  Recognized for expertise in <mark>JavaScript</mark> (particularly in ReactJS), with a proven track record of delivering high-quality code and optimizing user experiences. 
  
  Demonstrates leadership qualities by effectively collaborating within cross-functional teams, guiding junior developers, and driving projects to successful outcomes

  Committed to delivering high-quality code, optimising user experiences, and collaborating effectively within cross-functional teams.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Bumble
        sub_title: Lead Frontend Engineer
        caption: Feb 2018 - Present
        quote: "Led and contributed to diverse projects over 6 years at Bumble, London (UK), showcasing technical expertise and fostering teamwork for achieving exceptional results."
        skills: "Javascript, ReactJs, jQuery, CSS, SASS, Material-UI, Webpack, CSSinJS, Stencil.js, "
        list:
          - text: Led projects and teams overseeing the entire software lifecycle from requirement gathering to deployment.
          - text: Worked with client facing apps (Bumble web, Badoo web) and developed several internal tools.
          - text: Collaborated with cross-functional teams to gather requirements, design, and implement features aligned with project specifications.
          - text: Optimised application performance through code refactoring, performance tuning.
          - text: Conducted thorough code reviews, offering constructive feedback, and mentored junior developers to foster team growth.
          - text: Proactively engaged in Bumble's hiring team, playing a pivotal role in conducting interviews and effectively selecting top-tier candidates.

      - layout: left
        title: Roposo
        sub_title: Frontend Engineer
        caption: Dec 2015 - Jan 2018
        quote: "Worked at a small startup company in India, gaining valuable exposure to a diverse range of technologies and projects."
        skills: "Javascript, ReactJS, Angular (v1), Node JS, Express JS, MongoDB, CSS, LESS, HTML, jQuery"
        list:
          - text: "Roposo Desktop & Mobile Web application: Contributed to the development of a greenfield responsive web application using ReactJS."
          - text: "Bloggers Tool: Acted as a full stack developer, utilising the MERN stack (MongoDB, Express.js, ReactJS, Node.js) for development."
          - text: "Internal Tool: Developed an internal tool for user management, leveraging Material UI."

      - layout: left
        title: Tata Consultancy Services
        sub_title: Frontend Developer
        caption: Nov 2014 - Nov 2015
        quote: "Worked at a large scale MNC company in India, gaining valuable exposure to frontend development."
        skills: "Javascript, jQuery, Angular (v1), CSS, HTML"
        list:
          - text: Responsible for developing robust frontend applications working on jQuery based tech-stack, ensuring high-quality and user-friendly interfaces.
          - text: Played a key role in successfully migrating application from jQuery to AngularJS, enhancing performance and maintainability.

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: USICT, GGSIPU
        sub_title: B.Tech in Information Technology
        caption: 2010 - 2014
        description: |
          Achieved B.Tech (Bachelor of Technology) degree with a GPA of <mark>75.18</mark> (Equivalent to: First-Class Honours) from University School of Information, Communication and Technology (USICT) main campus of (GGSIPU) Guru Gobind Singh Indraprastha University, New Delhi, India.
        sub_description_heading: "Internship: RUBUS LABS Blackberry India"
        list: 
          - text: Web Developer Intern
          - text: September 2013
          - text: Developed a few web-based app for Blackberry10 OS, working with HTML5, CSS3, JavaScript, and jQuery.

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Front End Development Program
        sub_title: Free Code Camp
        caption: Issued Dec 2016
        link: https://www.freecodecamp.org/certification/gandhirahul/legacy-front-end
        link_text: Certificate
        quote: Completed Free Code Camp's rigorous Front End Development Program
        list: 
          - text: Completed FE dev program representing approximately 300 hours of work.
          - text: Acquired advanced proficiency in modern web development technologies and best practices.
          - text: Demonstrated expertise in building responsive and accessible user interfaces, optimizing performance, and implementing industry-standard design patterns.
          - text: Proven ability to mentor and coach junior developers, fostering a collaborative learning environment and accelerating team growth.

  - title: Scholastic Achievements
    layout: text
    content: | #
        | ----------- | ----------- |
        | 2014   | Received cash reward in Tizen Developer Offer competition.        |
        | 2013   | Won Devworx Blackberry 10 Competition and received a cash reward in Blackberry10 Port-a-Thon competition.        |
        | 2010   | Achieved All India Rank <b>254</b> in CET (Common Entrance Test).        |

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In my free time, I enjoy engaging in various activities that keep me active and intellectually stimulated. 
      
      I have a passion for playing table tennis and badminton. 
      
      Additionally, I love the tranquility and adventure of hiking and trekking, exploring nature's wonders and pushing my physical boundaries.
    
      I also prioritize my health and well-being, often spending time in the gym to maintain an active lifestyle and foster mental clarity. 
      
      When winding down, I immerse myself in self-help books, seeking personal growth and development, or delve into tech articles/videos to stay updated on the latest industry trends and advancements.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
